[package]
name = "pong"
version = "0.1.0"
authors = ["Julia Naomi <jnboeira@outlook.com>", "Ot√°vio Pace <otaviopp8@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ggez = "0.5.1"